### ISSUE TITLE
Targeting .NET Standard

### ISSUE THREAD

**Issue by gdziadkiewicz** [Offline24/NSubstituteFSharpWrapper#3]
I want to use your package in my .NET 4.5.2 project.

> Install-Package : Could not install package 'NSubstituteFSharpWrapper 1.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are 
> compatible with that framework. For more information, contact the package author.
> At line:1 char:1
> + Install-Package NSubstituteFSharpWrapper -Version 1.1.0
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by Offline24** [comment]
Thank you for your contribution (#4),
new version of package is available [(nuget)](https://www.nuget.org/packages/NSubstituteFSharpWrapper/1.2.0).
